### ISSUE TITLE
ISTA-Patcher 1.2.1 fails to patch.

### ISSUE THREAD

**Issue by CharlesJung73** [tautcony/ISTA-Patcher#10]
Hi~

I have been using ISTA-Patcher very well and I am always grateful to you.

There seems to be a bug in ISTA-Patcher 1.2.1.

My ISTA version is 4.42.20 and the command I ran is below.

`ISTA-Patcher.exe patch --enable-enet "A:\ISTA"`

After patching, folders "@ista-patched" and "@ista-backup" are created, but "@ista-patched" is empty and "@ista-backup" has the same files as the original.

Of course, the original files are not patched either.

ISTA-Patcher 1.2.0 worked fine, but this is a problem with 1.2.1.

Please check it out. ^^;

Environment :
 - Windows 11 Pro x64 (22621.1848)
 - Windows Terminal 1.17.11461.0
 - BMW_ISPI_ISTA-APP_4.42.20.25643.msi

![ISTA-Patcher](https://github.com/tautcony/ISTA-Patcher/assets/51778920/acd35b95-74b7-4d39-96a4-5240393f2d1e)

**Comment by iggy2022** [comment]
hello

have you tried running it twice?

**Comment by CharlesJung73** [comment]
No. I only ran it once.

This is the result of patching with ISTA-Patcher 1.2.0 against the same folder.

![Ista-Patcher_1 2 0](https://github.com/tautcony/ISTA-Patcher/assets/51778920/2ec579ee-0c42-4c75-a474-d301a7424e41)

**Comment by CharlesJung73** [comment]
I run ISTA-Patcher 1.2.1 twice, the first time it skips everything and the second time it does the patching normally. ^^

![Ista-Patcher_1 2 1 TwiceRun](https://github.com/tautcony/ISTA-Patcher/assets/51778920/a4acd87b-bc98-43ad-a7ca-153e4268a2e1)

**Comment by iggy2022** [comment]
glad to have helped you out
Is there a way to contact each other privately?
TC will fix this problem for us thanks to him
sorry for my English

**Comment by tautcony** [comment]
Try [this](https://github.com/tautcony/ISTA-Patcher/actions/runs/5567930790), the first run incorrectly skipped writing result during the backup process.

Restore all the programs, delete both `@ista-patched` & `@ista-backup` and try again.

**Comment by tautcony** [comment]
Bugfix version released: https://github.com/tautcony/ISTA-Patcher/releases/tag/v1.2.2

**Comment by iggy2022** [comment]
Thanks Tautcony
