### ISSUE TITLE
In ISTA 4.42.41, the "Execute Measures Plan" button is not active.

### ISSUE THREAD

**Issue by CharlesJung73** [tautcony/ISTA-Patcher#11]
Until ISTA 4.42.30, patching with ISTA-Patcher 1.2.3 enabled normal diagnosis, error deletion, and programming.

However, the "Execute Measures Plan" button is not active from ISTA 4.42.41, so only diagnostics and error deletion are possible.

The latest version of ISTA 4.43.13 shows the same symptoms.

Also, in ISTA 4.34.13, the contents of the file version information window look different than before.

I am sharing the ISTA app of the versions I mentioned just in case you need them.

https://mega.nz/folder/ixI2DADY#XnU-RoniuR1rveRQWq6kUQ

![4 42 41 25668](https://github.com/tautcony/ISTA-Patcher/assets/51778920/697037a0-5d58-48cf-8967-f880ae0c19d3)
![4 43 13 26115](https://github.com/tautcony/ISTA-Patcher/assets/51778920/6f1c87e8-e1c0-43ad-b902-560f1de8dda7)

**Comment by CharlesJung73** [comment]
When I tested again yesterday, the "Execute Measures Plan" button was activated in ISTA 4.42.41. I don't know why it didn't work before, but anyway, I'm glad it's active now~ :)

In ISTA 4.43.13, the "Execute Measures Plan" button is still not active.

I checked the logs by version, but the amount is huge and the contents are not easy to see.

In 4.42.41 and 4.43.13, I deleted the timestamp from the log file with the file name [date]_[account]_ISTA.log and compared it mainly with ERROR and WARNING, but there were about 3 errors that were not there before.

```
ERROR [T] ISTA: [1] ServiceLocator.GetService() - No service registered for type 'BMW.Rheingold.CoreFramework.Contracts.FASTA.IFasta2Service'. Using default instead.

ERROR [T] ISTA: [1] SQLiteConnectionMgr.InitializeXmlValuePrimitiveDb() - File C:\EC-APPS\ISTA\SQLiteDBs\xmlvalueprimitive_ENGB.sqlite not found, no connection to XmlValuePrimitive.

ERROR [T] ISTA: [1] SQLiteConnectionMgr.InitializeXmlValuePrimitiveDb() - File C:\EC-APPS\ISTA\SQLiteDBs\xmlvalueprimitive_DEDE.sqlite not found, no connection to XmlValuePrimitive.

```

Note that SQLiteDBs installed en-US instead of en-GB, and only en-US language is registered in the registry.

**Comment by iggy2022** [comment]
Hi
Charles Jung 73 do you have a link to download the latest full version for ista? and Cherry on the cake in French? here in france no way to find free SQLiteDBs fr it's paying and expensive
thanks in advance

**Comment by CharlesJung73** [comment]
I don't have a file of French SQLiteDBs.
If you need the latest version of the English SQLiteDBs file, I can share it.
