### ISSUE TITLE
4.44.1x update crashes on startup

### ISSUE THREAD

**Issue by itstheodor** [tautcony/ISTA-Patcher#14]
**Describe the bug**
Starting with update 4.44.1x, it seems BMW is starting to roll out some kind of authentication in ISTA. A quick look inside "RheingoldPresentationFramework" shows the BMW.Rheingold.PresentationFramework.Authentication class. I am not sure if it was there before, but that is where it crashes according to the logs (see uploads).

**To Reproduce**
1. Try launching ISTA 4.44.11

**Logs**
If applicable, upload logs under `ISTA\Logs` to help troubleshoot your problem (emptying the `Logs` folder and reproducing the problem before uploading them would be more helpful in analyzing the logs).
[20231030_031302_953b5ad6-bad3-464b-a941-6526f274fa05_IstaServicesHost.log](https://github.com/tautcony/ISTA-Patcher/files/13199822/20231030_031302_953b5ad6-bad3-464b-a941-6526f274fa05_IstaServicesHost.log)
[20231030_ISTA.log](https://github.com/tautcony/ISTA-Patcher/files/13199823/20231030_ISTA.log)

**Desktop (please complete the following information):**
 - OS Version: Windows 11 Pro, edition 22H2, build 22621.2428
 - ISTA Version 4.44.11
 - ISTA Edition original

**Comment by tautcony** [comment]
Yes, this class was not there before, as I haven't got the `4.44.11` version yet, could you please upload the `TesterGUI` folder for further investgation?

**Comment by itstheodor** [comment]
Will upload immediately as I get to my laptop. Can you email me on
me [at] theodor [dot] io
So that I don't upload them here? I don't want the repo to get taken down. If you insist, I'll put them here after all

**Comment by tautcony** [comment]
Try the version from [new branch](https://github.com/tautcony/ISTA-Patcher/actions/runs/6694404916).

`Authentication` here refers to the authentication of its online account system, which should be an unnecessary part here, corresponding function has been patched. But I'm not sure if there's still some blocking points behind it.

**Comment by itstheodor** [comment]
Still crashes at `BMW.Rheingold.PresentationFramework.Authentication.UserEnvironmentProvider.GetCurrentNetworkType`

[20231030_192135_b19c0c2e-8968-413b-a62c-980d2073f2ed_IstaServicesHost.log](https://github.com/tautcony/ISTA-Patcher/files/13207950/20231030_192135_b19c0c2e-8968-413b-a62c-980d2073f2ed_IstaServicesHost.log)
[20231030_ISTA.log](https://github.com/tautcony/ISTA-Patcher/files/13207951/20231030_ISTA.log)

**Comment by itstheodor** [comment]
Made a short & quick PR. It now launches successfully and no errors are logged so far. Will try connecting to the car later, but it should work.
Should investigate further if those new authentication features affect any other areas of the app. Would be pretty bad for it to crash, for instance, during programming.

**Comment by itstheodor** [comment]
Tested on my F30 using ENET. Works OK, connected successfully, vehicle test worked & was able to do some basic ops (delete fault memory).
I consider this closed after merging.

**Comment by tautcony** [comment]
After comparing codes with version 4.43, in addition to the above, making sure that config `BMW.Rheingold.Auth.Enabled` is set to `false` should be fine (which is set to false in code by default).

**Comment by itstheodor** [comment]
Yes, I set that to false. Should it be added to the README?
