### ISSUE TITLE
Latest version supported?

### ISSUE THREAD

**Issue by CharlesJung73** [tautcony/ISTA-Patcher#2]
I tried using ISTA-Patcher in ISTA 4.39.2x, but it doesn't run normally and there is an error.

Do you have any plans to update ISTA-Patcher to support the latest version?

![ISTA Error](https://user-images.githubusercontent.com/51778920/207478275-cfce6e96-8659-444e-a64a-c16ae5933489.png)

**Comment by CharlesJung73** [comment]
Here are two download links of ISTA StandAlone 4.39.2x.

https://mega.nz/folder/1AkQwR4J#KxOOg3PHhV0A_9v-TLbkLg

https://cherry3838.synology.me/fsdownload/LxCNZH6wD/ISTA_4.39.2x

**Comment by CharlesJung73** [comment]
When I heard that another friend succeeded, I tested it on another PC and it worked well.

I will test the diagnosis and programming when I have time.

I'll use it thankfully! :)

**Comment by tautcony** [comment]
Diagnostics I tested is working, but programming initialization will failed, you can also try it.

Maybe I need to refactor the patch method to make each function work properly.

**Comment by CharlesJung73** [comment]
Here are two download links of ISTA StandAlone 4.39.2x.

https://cherry3838.synology.me/sharing/LxCNZH6wD

https://mega.nz/folder/1AkQwR4J#KxOOg3PHhV0A_9v-TLbkLg

I hope it helps if refactoring is necessary.

**Comment by CharlesJung73** [comment]
There is an error when diagnosing.

I couldn't even try to update the firmware.

<img width="327" alt="ISTA Error 01" src="https://user-images.githubusercontent.com/51778920/208239877-9f6f778b-dbbf-49d3-b58f-942dcc62f6dc.png">
<img width="327" alt="ISTA Error 02" src="https://user-images.githubusercontent.com/51778920/208239879-dfe3de50-a71e-4cf2-8f20-fa3d511c282b.png">

**Comment by tautcony** [comment]
Yes, the programming module still need more investigation to make it work properly.

**Comment by xpnglitch** [comment]
i think i know why programming isnt working, ive checked through the logs. i beleive the reason is due to the dealerID and another (distributionID? cant remember the name of the second ID) being 00... in pzdsdata logs it fails to load due to the 2 IDs being zero... usually with earlier versions you would set dealerID to 1 after inserting license. hope this helps, as i dont have the knowledge to find out where to change this :)

**Comment by tautcony** [comment]
```java

    private static String generateOrganizationId(int dealerId, int plantId) {
        String organizationId;
        if (dealerId == 0) {
            if (plantId == 0) {
                throw new PSdZArgumentException(PSdZErrorCodes.DEALER_ID_AND_PLANT_ID_MUST_NOT_BOTH_BE_0);
            }
            organizationId = Integer.toString(plantId, 16);
        } else if (plantId != 0) {
            throw new PSdZArgumentException(PSdZErrorCodes.EXACTLY_ONE_OF_DEALER_ID_AND_PLANT_ID_MUST_BE_0);
        } else {
            organizationId = Integer.toString(dealerId, 16);
        }
        return organizationId;
    }
```


According to the error message shown in psdz-core.jar file, I made a manual patch to PsdzServiceImpl.dll(4.39.20), which set DealerID to 1234 and plantID to 0, This may work or not.

Since this error is thrown by the psdz(which is a java application), if this path does not work, may need to patch `psdz-core.jar` to bypass this check.


[patch-psdz.zip](https://github.com/tautcony/ISTA-Patcher/files/10257508/patch-psdz.zip)

**Comment by xpnglitch** [comment]
wow that was quick!! :) ill test it out
im actually testing this on 4.38.3x do you think it willl be backwards compatible?

**Comment by xpnglitch** [comment]
ok, i wasnt able to test with 4.39... but using it with 4.38 has definitely done something.... it do longer throws the error in the logs... but as you suspected it throws a db error.

here is the same file but from 4.38.. my ista download wont finish anytime soon

[PsdzServl.zip](https://github.com/tautcony/ISTA-Patcher/files/10266582/PsdzServl.zip)

**Comment by tautcony** [comment]
@xpnglitch 
try this
[Psdz-v1.8.zip](https://github.com/tautcony/ISTA-Patcher/files/10266652/Psdz-v1.8.zip)

**Comment by xpnglitch** [comment]
ok, will try now

**Comment by xpnglitch** [comment]
had issues with my 4.38 install... going to try 4.39 in about an hour or so, as i finshed installing it

**Comment by xpnglitch** [comment]
@tautcony confirmed working

**Comment by tautcony** [comment]
> @tautcony confirmed working

thanks for the test, i'll work on adding it to this patcher.

**Comment by iggy2022** [comment]
thank for your great work
months of work for an incredible result
good work

**Comment by CharlesJung73** [comment]
> Psdz-v1.8.zip

Which of the three folders below should I apply the Psdz-v1.8.zip file to?

- host
- host64
- Release?

> @xpnglitch try this [Psdz-v1.8.zip](https://github.com/tautcony/ISTA-Patcher/files/10266652/Psdz-v1.8.zip)



> @xpnglitch try this [Psdz-v1.8.zip](https://github.com/tautcony/ISTA-Patcher/files/10266652/Psdz-v1.8.zip)

**Comment by CharlesJung73** [comment]
> @xpnglitch try this [Psdz-v1.8.zip](https://github.com/tautcony/ISTA-Patcher/files/10266652/Psdz-v1.8.zip)

Which of the three folders below should I apply the Psdz-v1.8.zip file to?

1. PSdZ\host
2. PSdZ\host64
3. TesterGUI\bin\Release\Release

**Comment by tautcony** [comment]
Follow the folder structure.

**Comment by tautcony** [comment]
That file is for 4.38, host or host64 i think.

**Comment by wesk1** [comment]
working fine in ver 4.49.40
