### ISSUE TITLE
"Execute Measures Plan" What are the steps to activate?

### ISSUE THREAD

**Issue by BMW-FANS** [tautcony/ISTA-Patcher#21]
、
HI.
ISTA Execute measures plan is not active.
Is it possible to modify the patch program so that it becomes active?
--enable-enet
Nothing worked
ISTA 4.46.40
![微信图片_20240429145539](https://github.com/tautcony/ISTA-Patcher/assets/168314800/cfb1cddd-17c4-4da1-a984-380404194645)
![微信图片_20240429145609](https://github.com/tautcony/ISTA-Patcher/assets/168314800/93971d7d-80c6-48de-be5d-972bc2e4450e)
![微信图片_20240429145616](https://github.com/tautcony/ISTA-Patcher/assets/168314800/ad996c46-caa6-48f6-8dca-f4a1f2be7a81)

**Comment by tautcony** [comment]
Please upload the operation log which is required to check if there is anything that could be improved, the pre-check in ISTA for "Execute measures plan" is complacated and has many factors that could affect this.

**Comment by gvelf** [comment]
Hi!
Sorry how to use this patch to ISTA activate?)

**Comment by CharlesJung73** [comment]
I patched it to version 2.3.0, and now the error doesn't work.

Thank you @tautcony
