### ISSUE TITLE
ISTA4.48.20 software cannot be started

### ISSUE THREAD

**Issue by renzhig** [tautcony/ISTA-Patcher#23]
ISTA+  4.48.2x Install Files:
https://mega.nz/folder/ogYXjDAZ#blMNjpbGuTRapUDQF-EmJw

Error picture:
![1](https://github.com/user-attachments/assets/755d266b-90b8-41e2-a4fc-db32ded5c6bf)

Error log:
[20240716_LAPTOP-BB9EDSJ8_ISTA.log](https://github.com/user-attachments/files/16243442/20240716_LAPTOP-BB9EDSJ8_ISTA.log)

**Comment by CharlesJung73** [comment]
I experienced the same issue.

As updated to 4.47.xx, "ClientConfiguration.enc" and "ClientConfiguration.xml" were not generated in "C:\ProgramData\BMW\ISPI\config\ILIAN\ISPI Admin Client\", resulting in the above error.

Up until version 4.48.14.28244, the patch process was successfully completed by following these steps:

1. Patch everything except "CommonServices.dll"
2. Run ISTA
3. "ClientConfiguration.enc" and "ClientConfiguration.xml" are created in "C:\ProgramData\BMW\ISPI\config\ILEAN\ISPI Admin Client\"
4. Close ISTA
5. Patch "CommonServices.dll"

However, in version 4.48.14.28244, using the above method results in the creation of the two files in "C:\ProgramData\BMW\ISPI\config\ILEAN\ISPI Admin Client\", but an error occurs.

**Comment by tautcony** [comment]
Some new code about unexpected account login, I will try to patch related function later.

**Comment by tautcony** [comment]
Try running the patch with the `--patch-user-auth' option from this [build](https://github.com/tautcony/ISTA-Patcher/actions/runs/9976501523). @CharlesJung73 @renzhig

**Comment by CharlesJung73** [comment]
I gave you the option you told me with the build you told me and patched it.
However, the same symptoms appear.

**Comment by tautcony** [comment]
> I've patched with new builds and options.
> 
> However, the same symptoms appear.

Any change in the log?

**Comment by CharlesJung73** [comment]
The log folder is empty.
ISTA log has not been generated.
[Uploading ista-patcher20240719.log…]()

**Comment by andrewmiskell** [comment]
I was able to upgrade from 4.48.1x to 4.48.2x (Application, SDP and Data) and patch using the CI build with the --patch-user-auth flag. ISTA came up without any issues. Still need to verify a diagnostics/programming session, but so far looks good.

**Comment by CharlesJung73** [comment]
The reason for the error is that the "ClientConfiguration.enc" and "ClientConfiguration.xml" files were not created as they were before.

Andrewmiskell's success is thought to be due to patching with 2 files.

Can't you solve the problem that 2 files are not generated after patching?

@andrewmiskell 

I'm sure there will be an error if I move the above 2 files elsewhere and run ISTA.
