### ISSUE TITLE
How to work Toyota?

### ISSUE THREAD

**Issue by Rouptchak** [tautcony/ISTA-Patcher#28]
Hi,

Do you need additional files or is there a patch option for Toyota?

Because when I choose Toyota in ISTA settings, it asks me to restart ISTA so I close and when I run again, it does not start at all, no error, nothing happens. I have to go to the registry to change the line and put it back in BMW.

I looked at the contents of RELEASE, there is no file containing TOYOTA:

"RheingoldToyotaLicenseHelper.dll",
"RheingoldToyotaWorker.dll",
"ToyotaLicense.dll",

**Comment by tautcony** [comment]
The option `-t T` is for toyota.

I don't know if toyota has a specialized version for ista, I've only done a simple adaptation of a random version I saw online earlier, which may or may not work well.

**Comment by Rouptchak** [comment]
I tested with -t T and now it launches and asks for a valid registered key. So toyota does not work.

However, can we remove the toyota option in the ISTA choice tab since it does not work?

**Comment by tautcony** [comment]
This project is for authorization-related processing, the goal is to make the program runnable. But this configuration you mentioned is mainly data-level processing, which is currently out of the scope of this project, and I'm not familiar with ista's configuration.

**Comment by Rouptchak** [comment]
sorry my english is not very good to understand sometimes.
What I want to ask is can we delete this choice circled in the photo
![1](https://github.com/user-attachments/assets/24081d81-6313-4b44-97a7-9a9ce9df8338)

**Comment by tautcony** [comment]
As I said, it's a configuration issue, for example, I've never seen this option.

![](https://github.com/user-attachments/assets/c1f4d512-18f8-468b-ba2d-d958d7401472)

**Comment by Rouptchak** [comment]
This toyota option appeared since patch version 2.3.0 for me... Strange

**Comment by Rouptchak** [comment]
first picture is ORIGINAL, 2nd is patch with ISTA-Patcher patch -f --patch-user-auth --enable-enet C:\ISTA
![ori](https://github.com/user-attachments/assets/32753f13-8a69-45c3-8d89-a79d86fc6bf8)
![patch](https://github.com/user-attachments/assets/ff81af89-84d7-4ca0-8953-ac368be84106)

**Comment by Rouptchak** [comment]
I see toyota so I tried just like rollsroyce.

So if toyota is useless, I would like to remove it from the choice list but it is related to the patch and not to the config files

**Comment by tautcony** [comment]
The patcher didn't specifically add this option, need more feedback if this happens with other versions or devices.

**Comment by Rouptchak** [comment]
ok so why just before patching, toyota is not present?

Do you need file to see something?

**Comment by oxygen155** [comment]
> ok so why just before patching, toyota is not present?


I think it's not from patching, but from editing ISTAGUI.exe.config file. Some line enables full dev/debug mode with all the brands.
Try to compare original file with the one you have edited.

**Comment by Rouptchak** [comment]
This comes from the registry file, I found this by decoding:

**Comment by Rouptchak** [comment]
Solved, delete brand TOYOTA in Source code
