### ISSUE TITLE
RheingoldDatabasePostgreSQLConnector.dll is not found.

### ISSUE THREAD

**Issue by CharlesJung73** [tautcony/ISTA-Patcher#3]
Thank you for your work.

I have a question.

During a patch operation, a message appears stating that the file RheingoldDatabasePostgreSQLConnector.dll does not exist.

**"RheingoldDatabasePostgreSQLConnector.dll *************** [not found]"**

I checked the ISTA versions and found that the DLL file exists up to 4.38.14, but 4.39.11 and 4.39.20 do not contain that DLL file.

Can I just ignore it?

**Comment by tautcony** [comment]
It is generally ignorable, if the file does not exist, then there is no need for a patch.

**Comment by CharlesJung73** [comment]
I appreciate your kind reply.

The diagnosis was successful today and I will let you know after the firmware update test when the weather gets warmer.

**Comment by tautcony** [comment]
Glad to help, and thanks for testing.

**Comment by iggy2022** [comment]
hello all
other file not found
INF] PsdzServiceImpl.dll *************** [not found]
I guess it's in realise folder
version 4.35.18
have a good christmas

**Comment by CharlesJung73** [comment]
In the latest version of ISTA 4.39.2x, the patch was successful except that the file RheingoldDatabasePostgreSQLConnector.dll was missing.

Try the latest version.

https://mega.nz/folder/1AkQwR4J#KxOOg3PHhV0A_9v-TLbkLg

**Comment by iggy2022** [comment]
Thank you for the link
it is being downloaded
would you have for french ?? sorry tautcony this has nothing to do here
thank you for your work

**Comment by S0PEX** [comment]
@CharlesJung73 
Is this the latest version of ISTA?

**Comment by CharlesJung73** [comment]
> @CharlesJung73 Is this the latest version of ISTA?

In the StandAlone version, this is the latest version.

Delta Update (4.29.20 → 4.39.21) was recently released.

https://mega.nz/folder/Ogol1JaT#7Lx1Vtvk77G6ztBDpgSrWQ

The program is not updated, only the data for the S15c vehicle has been updated.

So you do not need to update it unless it is an S15c vehicle.

**Comment by iggy2022** [comment]
@CharlesJung73 
have you link for french version ?
