### ISSUE TITLE
bug in --help arg

### ISSUE THREAD

**Issue by botho** [tautcony/ISTA-Patcher#33]
Bug into --help argument

Runnning **"ISTA-Patcher.exe" -h** only show these (few information)
Description:
  Copyright (C) 2022-2024 TautCony.
  Repo: https://github.com/tautcony/ISTA-Patcher
  Released under the GNU GPLv3+.

Usage:
  ISTA-Patcher [command] [options]

Options:
  -?, -h, --help  Show help and usage information
  --version       Show version information

Commands:
  patch <targetPath>    Perform patching on application and libraries. []
  cerebrumancy          Initiate operations related to the manipulation of consciousness.
  decrypt <targetPath>  Decrypt the integrity checklist. []
  ilean                 Perform operations related to iLean.

--------

But when Runnning "ISTA-Patcher.exe" --Wrong args, then info are more precise
**Unrecognized command or argument 'C:\EC-APPS\ISTA'**.

Description:
  Perform patching on application and libraries.

Usage:
  ISTA-Patcher patch [<targetPath>] [options]

Arguments:
  <targetPath>  Specify the path for ISTA-P. Provide the full path where ISTA-P is located on your system. []

Options:
  -v, --verbosity                                  [Element] Set the output verbosity level of the ISTA-Patcher's
  <Debug|Error|Fatal|Information|Verbose|Warning>  output. [default: Information]
  -r, --restore                                    [General] Restore patched files to their original state. [default:
                                                   False]
  --enable-enet                                    [Adjunct] Enable ENET programming functionality. [default: False]
  --enable-finished-op                             [Adjunct] Enable to open finished operations. [default: False]
  --disable-requirements-check                     [Adjunct] Disable system requirements check functionality. [default:
                                                   False]
  --enable-not-send                                [Adjunct] Enable VIN Not Send Data functionality. [default: False]
  --skip-validation-patch                          [Adjunct] Skip license validation patch. [default: False]
  --enable-offline                                 [Adjunct] Enable offline functionality. [default: False]
  --patch-user-auth                                [Adjunct] Patch user authentication environment. [default: False]
  --market-language                                [Adjunct] Set the market language. []
  --skip-sync-client-config                        [Adjunct] Skip sync client configuration. [default: False]
  --max-degree-of-parallelism                      [Adjunct] Set the maximum degree of parallelism for patching.
                                                   [default: 4]
  -t, --type <B|T>                                 Specify the patch type. Valid options: B, T. [default: B]
  --generate-registry-file                         Generate a registry file. [default: False]
  -d, --deobfuscate                                Enable deobfuscation of the application and libraries. [default:
                                                   False]
  -f, --force                                      Force patching on application and libraries. If specified,
                                                   ISTA-Patcher will apply patches forcefully, bypassing certain
                                                   checks. [default: False]
  --skip-library                                   Specify the library to skip patching. []
  -?, -h, --help                                   Show help and usage information

**Comment by tautcony** [comment]
This is how [`System.CommandLine`](https://learn.microsoft.com/en-us/dotnet/standard/commandline/) in `ISTA-Patcher` works, it has 2 layers, first layer is the `command` layer, its help message can be shown with `ISTA-Patcher --help`, second layer is under each `command`, and does the actual work.

Take `patch` as an example, `ISTA-Patcher patch` will take specific options to work with the `patch` `command`. `--help` is an option, with `ISTA-Patcher patch --help` you will see the help message for the `patch` `command`, as well as the rest of the commands.

**Comment by botho** [comment]
Fine, didn't understand this 2 layers of helps. Sorry.
