### ISSUE TITLE
[Feature request] Disable Fake FSC Reject

### ISSUE THREAD

**Issue by OrpheeGT** [tautcony/ISTA-Patcher#34]
Hello,

Some users are reporting ISTA Patcher lacks of a "standalone" feature known as "DisableFakeFSCReject".

I'm not able to confirm it myself as I don't have a compatible car to test.

But genuine ISTA discarde/delete fake FSC added (with E-Sys I guess ?).
It is expected from genuine unmodded ISTA, but it used to be patched on "old" standalone release...

Could this feature be added to ISTA Patcher ?

Thanks

**Comment by OrpheeGT** [comment]
I will try to ask for it.

**Comment by tautcony** [comment]
send via email `tautcony#gmail` @OrpheeGT

**Comment by tautcony** [comment]
Rewrite the periodicalCheck to `false` in commit with option `--disable-fake-fsc-reject` in commit a6525689eeeb740f090c3c2deb5775e07e317a23

**Comment by OrpheeGT** [comment]
Built and sent to some testers!
