### ISSUE TITLE
Installation file decompilation request

### ISSUE THREAD

**Issue by roadray** [tautcony/ISTA-Patcher#6]
I would like to ask if it is possible to decompile the attached installation file.

https://mega.nz/file/z1JDhToL#QKLuIu8dKDdumAZARpNNH57z9BS34aA8uZwj6SytMmw

**Comment by tautcony** [comment]
I don't get your point, this setup is just an executable file generated by Inno Setup. It contains only the installation script with its required dependencies, and to some extent does not contain any files related to ISTA-P.

**Comment by roadray** [comment]
I want to make the install file with the same conditions.
I would like to modify some of the contents for the installation file execution, but I am currently unable to do so, so I am inquiring.

**Comment by tautcony** [comment]
I'm not too familiar with Inno Setup repackaging, so I don't have any specific advice to offer you. However, I suggest checking out the tool's documentation or support resources to see if they can help you out.

**Comment by tautcony** [comment]
That requires provide the log files under `.\EC-APPS\ISTA\Logs`. Both application log and 
istaOperation log are required.

I need to confirm if there is any associated exception log.

**Comment by roadray** [comment]
We will send you a link to the file.
https://mega.nz/file/nlRwlQgY#d1YwOusrX5-xUZu1RlsKi6Y_fFNyZlXoxt--zvXQjDQ
thank you.

**Comment by tautcony** [comment]
There are no new exception messages, except for the logs caused by deserialization failure, and the following actions may help:

Save following as "license.reg" and import this mock license information to avoid license deserialization exceptions.

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\BMWgroup\ISPI\Rheingold]
"License"="<?xml version=\"1.0\"?><LicenseInfo xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns=\"http://tempuri.org/LicenseInfo.xsd\"><Name>BMW Group MOSSR2</Name><Email>your_email_here@bmw.de</Email><Expiration>2099-05-01T00:00:00</Expiration><Comment /><ComputerName xsi:nil=\"true\" /><UserName>*</UserName><AvailableBrandTypes>*</AvailableBrandTypes><AvailableLanguages>*</AvailableLanguages><AvailableOperationModes>*</AvailableOperationModes><DistributionPartnerNumber>*</DistributionPartnerNumber><ComputerCharacteristics>wePC9Q9xawMjVPA2fkMVvioHNtA=</ComputerCharacteristics><LicenseKey>dGhpcyBpcyBrZXkK</LicenseKey><LicenseServerURL xsi:nil=\"true\" /><LicenseType>offline</LicenseType></LicenseInfo>"
```
