### ISSUE TITLE
Failed to start ISTA

### ISSUE THREAD

**Issue by Rouptchak** [tautcony/ISTA-Patcher#8]
Hi

Is the patch good for switching a native version to standalone?

Because it doesn't work for me.

Failed to start ISTA.
Please make sure your ISTA configuration is valid.
In doubt reset any non standard ISTA configuration and reinstall ISTA.

Registry information is done.

And in patch, file RheingoldDatabasePostgreSQLConnector.dll not found.

Not present in version 4.40

**Comment by Rouptchak** [comment]
Folder Logs is empty.

**Comment by tautcony** [comment]
```csharp
Log.Error("App.Init()", "Failed to start ISTA: {0}", new object[] { ex });
```

Theoretically there should be a line of exception information written down, it may be that the exception was been thrown too early. Based on the current information, it may not be possible to locate the problem.

**Comment by Rouptchak** [comment]
your patch only works on versions already patched by sedoy to circumvent its license.
Therefore not suitable for an original installation with ISPI. Which explains why I can't launch the software.

**Comment by tautcony** [comment]
Since I don't have the original program yet, I can only develop based on what I have access to and patch some limitations.

Could you please provide the original `TesterGUI` for comparison, I will see if there is a possibility to adapt with the original program.

**Comment by Rouptchak** [comment]
Here

https://mega.nz/file/AFQlwRxY#eSCCcJEP1CvO6LXxTcHASFIFTHNFObdtcbG_Gi44cdQ

**Comment by tautcony** [comment]
I checked the code for GUI initialization and there is no significant difference from the old one(eg: 4.37). The possible cause of this exception may be that the dealer data is not initialized correctly which leading to an `NPE`.

Accroding to the code, if both `IsILeanActive` and `OSSModeActive` are false, the program would load the default dealer data. When I change one of these two options to true, it does reproduce the same error message.

Therefore, the following two parameters must either not exist in the registry or in the config file, or be explicitly configured as `false`. You may check these specific configuration.

- `BMW.Rheingold.CoreFramework.ILeanActive`
- `BMW.Rheingold.CoreFramework.OSSModeActive`

**Comment by CharlesJung73** [comment]
I fixed it by installing Microsoft Visual C++ Redistributable.

Try installing both x64, x86 versions, restarting Windows, and running ISTA.

x86 : https://aka.ms/vs/17/release/vc_redist.x86.exe
x64 : https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by Rouptchak** [comment]
It was working fine until I decided to revert to original and then repatch. And since then I have this error again.

Failed to start ISTA.
Please make sure your ISTA configuration is valid.
In doubt reset any non standard ISTA configuration and reinstall ISTA.

I updated to 4.41, repatched and still the same. I tested on 2 other PCs, one of which was recently reinstalled and impossible to make it work again, I don't understand.

Patch v1 or 1.2
Clean registry
Framework ok
vc redist all ok

**Comment by Rouptchak** [comment]
Ista 4.40 started correctly after installing vc redist 2022 and patch.
I reinstalled Ista properly with ispi admin client, I repatched by testing v1.2 and since then the error has returned and yes the log file is still empty.

I redid with v1.0 but v1.1 is still error too. Curious problem

I put ista 4.41 and the same.

**Comment by tautcony** [comment]
Please upload the patched ISTAGUI.exe(4.41), I need add some additional modificaions in order to show  the exception message.

**Comment by Rouptchak** [comment]
https://mega.nz/file/pIpGyTpY#sZ-n2A8WfSbIdW9jfKS0G6SBDwWJqsPiIPz4hWe0WE8

**Comment by tautcony** [comment]
[ISTAGUI4.41.modified.exe.zip](https://github.com/tautcony/ISTA-Patcher/files/11478883/ISTAGUI4.41.modified.exe.zip)

This edition may show some more details about the exception.

**Comment by Rouptchak** [comment]
Ista does not launch with your exe

**Comment by tautcony** [comment]
The error dialog didn't show up?

**Comment by Rouptchak** [comment]
nothing happens at launch, no window

**Comment by Rouptchak** [comment]
Same, not run.

**Comment by tautcony** [comment]
![ISTA-4 41-Screenshot](https://github.com/tautcony/ISTA-Patcher/assets/8295052/3831ce2e-3c63-4826-af77-42ba5addee20)

hmmm, I found a copy and tested it. This patcher is workable with 4.41.21.

**Comment by Rouptchak** [comment]
ok i don't understand my problem. Standalone 4.37 works correctly, 4.40 or 4.41 official offline license works correctly, 4.40 worked patched but once reinstalled official then repatched, it hasn't worked since.

Can you send me the release folder that I check if there is a difference?

**Comment by tautcony** [comment]
Since I didn't find an original version, this is also a version that has been modified by someone and expect to profit from the sale of activation. Since the number of files modified varies from patching method to patching method. So I'm not sure how many files he actually modified, at least ISTAGUI was modified, just replaced ISTAGUI.exe and run ISTA-Patcher, it could be launched normally.

You may check release folder from [this link](https://mega.nz/file/AEQTHKja#acrqKrq2c88vEclkhPT57_6idnx-0XYQrYnxeGdtMyo)

**Comment by Rouptchak** [comment]
Thank you for your answers and your work but I give up.

I try, redo clean from the beginning, change pc but nothing helps. I will be content with my ispi license on the main pc.
